export const SERVER_HOST_URL =
  process.env.NEXT_PUBLIC_SERVER_HOST || "http://localhost:4000";

export const INITIAL_PAGE = 1;
export const MAX_TEXT_CONTENT_LENGTH = 1000;

export enum Audience {
  PUBLIC,
  FOLLOWERS,
  FRIENDS,
  VERIFIED,
  ONLY_ME,
}

export enum Privacy {
  PUBLIC,
  FOLLOWERS,
  FRIENDS,
  PRIVATE,
}

export enum TrendingReportType {
  NOT_RELEVANT,
  SPAM,
  ABUSIVE,
  NOT_INTERESTED,
  DUPLICATE,
  HARMFUL,
}

export enum SearchItemType {
  USER,
  QUERY,
  HASHTAG,
  POST,
  MEDIA,
}

export enum StoryBackground {
  BLUE_GRADIENT,
  PINK_PURPLE_BLUE_GRADIENT,
  MAGENTA_ORANGE_YELLOW_GRADIENT,
  DOWNY,
  MANDY,
  PERSIAN_BLUE,
  SOLID_BLACK,

  PURPLE_WAVY_LINE,
  PINK_TOPOGRAPHY,
  GRAY_STAIRS,
  RED_ZIG_ZAG,
  LIGHT_GRAY_WEAVE,
  STARRY_NIGHT,
  CARBON,

  ARGYLE,
  GRAY_CUBE,
  TARTAN,
  TEAL_CICADA_STRIPES,
  BLACKBERRY_ENDLESS_CONSTELLATION,
  ORANG_FLAT_MOUNTAINS,
  GREEN_HOLLOWED_BOXES,

  GREEN_TORTOISE_SHELL,
  TEAL_ROTATED_SQUARES,
  YELLOW_LIQUID_CHEESE,
  FLAMINGO_PROTRUDING_SQUARES,
  PURPLE_TO_PINK_SUBTLE_PRISM,
  SPECTRUM_GRADIENT,
  BLACK_WAVEY_FINGERPRINT,

  RADIENT_GRADIENT,
  ORANGE_SUN_TORNADO,
}

export enum NotificationType {
  ALL = "all",
  SECURITY = "security",
  SOCIAL = "social",
  POST = "post",
  REQUEST = "request",
  MENTION = "mention",
  FOLLOW = "follow",
}

export enum ExploreType {
  MEDIA = "media",
  POST = "moments",
}
